name: Github Action Demo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        env:
          CI: true

      - name: Initialize Google Cloud SDK & Deploy
        uses: etereo-io/deploy-gae-action
        with:
          service_account: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          gae_config_path: "./app.yaml"
          debug: true
          no_cache: false
          dispatch_yaml: ""
